#pragma config(Sensor, S2, ,     sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IR Seeker Modes
0 - modeEV3IR_Proximity
1 - modeEV3IR_Seeker
2 - modeEV3IR_Remote
3 - modeEV3IR_Remote_Advanced
5 - modeEV3IR_Calibration
*/

/*
IR Remote Mode Values:
0 - No button (and Beacon Mode is off)
1 - Button 1
2 - Button 2
3 - Button 3
4 - Button 4
5 - Both Button 1 and Button 3
6 - Both Button 1 and Button 4
7 - Both Button 2 and Button 3
8 - Both Button 2 and Button 4
9 - Beacon Mode is on
10 - Both Button 1 and Button 2
11 - Both Button 3 and Button 4

Remote Layout:

-------
[1]	[3]
[2] [4]
-------
*/

typedef enum IRState
	{
		nonePressed,
		forwardLeft,
		backLeft,
		forwardRight,
		backRight,
		forwardFull,
		spinRight,
		spinLeft,
		backFull,
		beaconState,
		leftFull,
		rightFull,
	} IRState;

IRState getIRState(void)
{
	int IRButton = 0;

	while(true)
	{
		IRButton = getIRRemoteButtons(S2);

		switch(IRButton)
		{
            case 0:
                return nonePressed;
            case 1:
                return forwardLeft;
            case 2:
                return backLeft;
            case 3:
                return forwardRight;
            case 4:
                return backRight;
            case 5:
                return forwardFull;
            case 6:
                return spinRight;
            case 7:
                return spinLeft;
            case 8:
                return backFull;
            case 9:
                return beaconState;
            case 10:
                return leftFull;
            case 11:
                return rightFull;
		}
	}
}

