#pragma config(Sensor, S2,     IRreceiver,     sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IR Seeker Modes
0 - modeEV3IR_Proximity
1 - modeEV3IR_Seeker
2 - modeEV3IR_Remote
3 - modeEV3IR_Remote_Advanced
5 - modeEV3IR_Calibration
*/

/*
IR Remote Mode Values:
0 - No button (and Beacon Mode is off)
1 - Button 1
2 - Button 2
3 - Button 3
4 - Button 4
5 - Both Button 1 and Button 3
6 - Both Button 1 and Button 4
7 - Both Button 2 and Button 3
8 - Both Button 2 and Button 4
9 - Beacon Mode is on
10 - Both Button 1 and Button 2
11 - Both Button 3 and Button 4

Remote Layout:

-------
[1]	[3]
[2] [4]
-------
*/

bool nonePressed, forwardLeft, backLeft, forwardRight, backRight, forwardFull,
		 spinRight, spinLeft, backFull, beaconState, leftFull, rightFull;


task main()
{
	int IRButton = 0;

	while(true)
	{
		IRbutton = getIRRemoteButtons(IRreceiver);

		switch(IRbutton)
		{
		case 0:
			return nonePressed = true;
		case 1:
			return forwardLeft = true;
		case 2:
			return backLeft = true;
		case 3:
			return forwardRight = true;
		case 4:
			return backRight = true;
		case 5:
			return forwardFull = true;
		case 6:
			return spinRight = true;
		case 7:
			return spinLeft = true;
		case 8:
			return backFull = true;
		case 9:
			return beaconState = true;
		case 10:
			return leftFull = true;
		case 11:
			return rightFull = true;
		}

		if (nonePressed == true)
		{

		forwardLeft = false;

		backLeft = forwardRight = backRight = forwardFull = spinRight = spinLeft =
		backFull = beaconState = leftFull = rightFull = forwardLeft;
	  }
	}
}

