//#pragma config(Motor,  port10, myMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct PIDController{
	float pidIntegral;
	float pidDerivative;
	float pidDrive;
	float pidLastError;

	float maxOutput;
	float minOutput;

	float kP;
	float kI;
	float kD;

	float integralLimit;
	float target; // variable is used by drive straight controller
} PIDController;
 

void PID_initPIDConstants(PIDController *controller, float p, float i, float d, float integralLimit)
{
	controller -> kP = p;
	controller -> kI = i;
	controller -> kD = d;
	controller -> integralLimit = integralLimit;
}

void PID_initOutputRange(PIDController *controller, float max, float min)
{
	controller -> maxOutput = max;
	controller -> minOutput = min;
}


void PID_reset(PIDController *controller)
{
	controller -> pidLastError = 0;
	controller -> pidIntegral = 0;
	controller -> pidDerivative = 0;
}

float PID_calculateDrive(PIDController *controller, float error)
{
		float drive;

		if(controller -> kI != 0 && controller -> pidIntegral < controller -> integralLimit)
			controller -> pidIntegral += error;
		if(controller -> pidIntegral > controller -> integralLimit)
			controller -> pidIntegral = controller -> integralLimit;
		
			

	  float derivative = error - (controller -> pidLastError);
	  controller -> pidLastError = error;

	  drive = (controller -> kP)*error + (controller -> kI)*(controller -> pidIntegral) + (controller -> kD)*derivative;
	  if(drive > controller -> maxOutput)
	  	drive = controller -> maxOutput;

	  if (drive < controller -> minOutput)
	  	drive = controller -> minOutput;

	  return drive;
}
